[build]
  command = "npm run build"
  publish = "out"

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/buy"
  to = "https://fearful-camera-9811.glideapp.io"
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/browse"
  to = "https://right-noise-9574.glideapp.io/"
  force = true

[[redirects]]
  from = "/beauty"
  to = "https://quarrelsome-plant-7288.glideapp.io"
  force = true

[[redirects]]
  from = "/health"
  to = "https://crooked-sponge-4983.glideapp.io"
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/fashion"
  to = "https://screeching-frame-9268.glideapp.io"
  force = true # COMMENT: ensure that we always redirect

