[build]
  command = "npm run build"
  publish = "out"

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/skincare"
  to = "https://quarrelsome-plant-7288.glideapp.io"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/shop"
  to = "https://fearful-camera-9811.glideapp.io"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/health"
  to = "https://screeching-frame-9268.glideapp.io"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/fashion"
  to = "https://screeching-frame-9268.glideapp.io/"
  status = 200
  force = true # COMMENT: ensure that we always redirect

